### ISSUE TITLE
Can the packaged executable file effectively protect the source code?

### ISSUE THREAD

**Issue by yumao233** [pmq20/node-compiler#156]
I hope to avoid leaking the JavaScript source code. I wonder if the packaged executable program can avoid this?

**Comment by mister-perfect** [comment]
I do not think the executable file would protect the source code. The data of the squashfs image is just a C array:
`const uint8_t enclose_io_memfs[#{bytes.size}] = { #{bytes[0]}"`. 
The hacker could decompile, extract these bytes then `mount xxx.sqsh /mnt/xxx`. All codes is here.

@Suwings

**Comment by Suwings** [comment]
thank you for your reply. 

Is the code obtained in this way readable Javascript? If it is difficult to understand Javascript code is also acceptable. Or are there other more ways to get readable Javascript code?

@mister-perfect
