### ISSUE TITLE
Generating a cli app in ubuntu

### ISSUE THREAD

**Issue by danielvieiravega** [pmq20/node-compiler#18]
Hi,
After compiling my node cli app, I try to run the generated executable, but it outputs the following error: 
![capture](https://cloud.githubusercontent.com/assets/7685159/22561423/4ade9362-e95f-11e6-959e-ba77b595d01b.PNG)

**Comment by pmq20** [comment]
@danielvieiravega Thanks for reporting. It turns out Node.js takes use of all three read system calls, i.e., pread, read, readv, yet we only intercepted one of them to libsquash. I'm working on a fix.
