### ISSUE TITLE
armhf support?

### ISSUE THREAD

**Issue by thom-nic** [pmq20/node-compiler#26]
I'm running a nodejs app on an embedded device (think beaglebone black or raspberry pi).  For non-trivial projects, `npm install` takes a significant amount of time on a live device.  Instead I typically do the install from an x86 host using chroot and qemu-user-static.  It seems like this would be great for simplifying app distribution for embedded targets.  

I also use gcc-arm-linux-gnueabihf to cross-compile the kernel from x86 host,  if it's more manageable to specify a cross-toolchain and stay within the x86 host env instead of a chroot.

FWIW I also use several native modules (serialport, bcrpypt and node-sqlite) so would possibly be impacted by #25

**Comment by pmq20** [comment]
I have not tested it on ARM yet because of lack of devices. It should work as long as libsquash compiles on ARM since I remember that Node.js already works on ARM.

**Comment by pmq20** [comment]
Sorry for the delay. I am not an expert on cross compiling so I need some time to look into it. There is another PR that seems relevant. I'll reference it here https://github.com/pmq20/node-compiler/pull/36

**Comment by lexor90** [comment]
I'm going to merge support for cross-compilation so that you will be able to cross-compile using nodec, feedbacks are welcome since we didn't test it on an arm platform.

**Comment by lexor90** [comment]
Closing this in favor of #36 to avoid redundant issues. Feel free to re-open this should you need it.

**Comment by cnddu** [comment]
Guys, I met issue on armhf build, pls help take a look here #82 , thanks
