### ISSUE TITLE
"It should match the enclosed Node.js runtime version of the compiler."

### ISSUE THREAD

**Issue by maximumdata** [pmq20/node-compiler#27]
Just tried this out using the example provided by the CLI, and got this output:

```
Node.js Compiler (nodec) v0.9.5 (runtime 7.7.3)

It should match the enclosed Node.js runtime version of the compiler.
Expecting v7.7.3; yet got v7.8.0.
```

Obviously, my local version of node is 7.8.0. Does this mean I need to downgrade to 7.7.3 to use this tool? If so, this is not mentioned anywhere in the README.

**Comment by pmq20** [comment]
It does not seem to be a strict requirement. I'll upgrade the runtime to the latest 7.9.0 and consider changing this to a warning this weekend.

**Comment by jerson** [comment]
maybe v7.10.0 :)

**Comment by pmq20** [comment]
@jerson Thanks for pointing it out :) Landed in https://github.com/pmq20/node-compiler/commit/68ddd9c9e8ec67c2b037cff049468b363a04311d

Let's wait for the CI and I'll release nodec v0.9.6 once they are all green.

**Comment by pmq20** [comment]
Node.js Compiler v0.9.6 (runtime 7.10.0) released! @maximumdata Please check if it solves your problem, thanks!

https://github.com/pmq20/node-compiler/releases/tag/v0.9.6

**Comment by goforward01** [comment]
Hi, @pmq20 .For some reason, I used nodejs of version 6.10.3, the Latest Version of nodejs. Uh, actually the grpc module and protobuffer is quite strict about the nodejs version, so I'm wandering whether there are some other ways for node compiler to assign the version of nodejs.

**Comment by goforward01** [comment]
@pmq20, Uh, I just used node compiler to build my project, while as said before I used grpc in my project. After couples of minutes, the compile job is done and of course, I get the a.out. but it can't work, just like **pkg**, the other tool to bundle the nodejs application. The error result looks like:
```
module.js:598
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: /__enclose_io_memfs__/node_modules/grpc/src/node/extension_binary/grpc_node.node: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:488:32)
    at tryModuleLoad (module.js:447:12)
    at Function.Module._load (module.js:439:3)
    at Module.require (module.js:498:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/__enclose_io_memfs__/node_modules/grpc/src/node/src/grpc_extension.js:38:15)
    at Module._compile (module.js:571:32)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:488:32)
```
Maybe, node compiler has issue with the addons of nodejs, are there any suggestions about solving this problem?

**Comment by pmq20** [comment]
@goforward01 Thanks for the feedbacks. You have mentioned two problems,

1. One is the problem of binding nodec with a particular node runtime version. I believe the correct way to solve this is to make it available for the user to choose a runtime version (or read from the environment to determine her current used node version) and nodec shall download the source code for her and apply the patch ( the patch is very small so I am confident it should work across different node versions, most of the work being done by libsquash ).
1. The other problem is similar to https://github.com/pmq20/node-compiler/issues/29 and https://github.com/pmq20/node-compiler/issues/25

Since Problem Two has been raised at least three times, I'll start working on it right away. For Problem One I'll come back to it later. Keep tuned 😝

**Comment by goforward01** [comment]
@pmq20 ，Thanks for rapid reply. btw, nice job with node compiler project. And I'll keep an eye on it later on. Really excited about being able to compile node application to single runnable file, and taking times to make it better surely be a worthy thing to do. thxs for excellent work of this project.

**Comment by pmq20** [comment]
@goforward01 Node.js Compiler v1.0.0 released! Native C++ modules are fully supported now.

https://github.com/pmq20/node-compiler/releases/tag/v1.0.0

**Comment by goforward01** [comment]
@pmq20 Wow，that's awesome! I'll try it in a moment. Thanks for informing me,  and also thanks for the excellent work with **node-compiler**.

**Comment by goforward01** [comment]
@pmq20 , Hi, I gave a try to use v1.0.0, and it work fine with everything, while for some reasons I have to use the grpc@1.2.4, but I found the node version at default is v8.0.0, as show below:
```
./nodec --node-version
Node.js Compiler (nodec) v1.0.0 (runtime 8.0.0)

8.0.0
```
and my nodejs version is the LTS version of v6.10.3.So when I finished my compile process, of course, I got a.out file.While without luck, it reminded me I shouldn't use v8.0.0 to compile my grpc module.
```
module.js:598
  return process.dlopen(module, path._makeLong(filename));
                 ^

Error: The module '/__enclose_io_memfs__/node_modules/grpc/src/node/extension_binary/grpc_node.node'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 48. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at Object.Module._extensions..node (module.js:598:18)
    at Module.load (module.js:503:32)
    at tryModuleLoad (module.js:466:12)
    at Function.Module._load (module.js:458:3)
    at Module.require (module.js:513:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/__enclose_io_memfs__/node_modules/grpc/src/node/src/grpc_extension.js:38:15)
    at Module._compile (module.js:569:30)
    at Object.Module._extensions..js (module.js:580:10)
    at Module.load (module.js:503:32)
```
Uh, Is there anyway to used the specially appointed version of nodejs before compile the pro?

**Comment by pmq20** [comment]
@goforward01 I think this is the same issue with https://github.com/pmq20/node-compiler/issues/40   where @lexor90 has detailed proposal regarding supporting arbitrary node.js runtime versions. Let's discuss it there.

**Comment by lexor90** [comment]
Closing, let's talk to the referenced issue. Feel free to open it again should you need it.
