### ISSUE TITLE
Cannot complete the process on Linux

### ISSUE THREAD

**Issue by chintan39** [pmq20/node-compiler#30]
I am running on a 4 core and 4 GB ram machine, but not able to complete the process.

virtual memory exhausted: Cannot allocate memory
deps/libsquash/enclose_io_libsquash.target.mk:95: recipe for target '/tmp/nodec/node/out/Release/obj.target/enclose_io_libsquash/deps/libsquash/sample/enclose_io_memfs.o' failed
make[1]: *** [/tmp/nodec/node/out/Release/obj.target/enclose_io_libsquash/deps/libsquash/sample/enclose_io_memfs.o] Error 1
make[1]: *** Waiting for unfinished jobs....
make[1]: Leaving directory '/tmp/nodec/node/out'
Makefile:75: recipe for target 'node' failed
make: *** [node] Error 2
Failed running ["make -j4"]

**Comment by pmq20** [comment]
How big is your project folder? I.e. `/tmp/nodec/_work_dir_`.

**Comment by chintan39** [comment]
Its around 55 MB.

**Comment by pmq20** [comment]
weird. 55MB shouldn't cause low-memory. How big is `/tmp/nodec/node/out/Release/obj.target/enclose_io_libsquash/deps/libsquash/sample/enclose_io_memfs.c`? What's your gcc and g++ version?

**Comment by chintan39** [comment]
enclose_io_memfs.c is 38M
gcc and g++ version 
`gcc version 5.4.0 20160609 (Ubuntu 5.4.0-6ubuntu1~16.04.4)`

**Comment by chintan39** [comment]
Weird, I tried it again today and now it seems to work.

**Comment by pmq20** [comment]
@chintan39 `38M` is not a big size. Gcc `5.4` is also a sufficient compiler. I recommend turn off some processes to make room for the compiling process, which consumes quite a lot of system resources. Also, using a machine with a bigger RAM could help.
