### ISSUE TITLE
Created binary takes arguments or a configuration file @enhancement

### ISSUE THREAD

**Issue by chintan39** [pmq20/node-compiler#32]
This can help running a single binary on different servers with different databases or other  #custom configurations.

**Comment by pmq20** [comment]
Could you elaborate? I am having a hard time understanding the issue.

**Comment by chintan39** [comment]
Its an enhancement for future
Example : If we make a server executable , we will need to pass some configuration that will be dynamic like database IP, app ID, etc.

`./server --appId XXXX --mySQLIP "xx.xx.xx.xx"`

We need to read these arguments in Node.js

**Comment by pmq20** [comment]
You could already do so. Just implement it in your Node.js app by reading `process.argv`. Whatever works before compiling should also work after compiling.

**Comment by chintan39** [comment]
Great!!
Will try that and let you know

**Comment by chintan39** [comment]
It works!!
