### ISSUE TITLE
SquashFS Windows Install Instructions?

### ISSUE THREAD

**Issue by firrae** [pmq20/node-compiler#43]
Hi there,

I'm not 100% sure how to install the SquashFS you link to in the prerequisites section of the readme. I get that's it's pre-compiled but where do we put the file? I have tried putting it into the PATH on my Windows Server machine but to no luck so far. Any further instruction would be helpful.

Thanks,

Steve

**Comment by pmq20** [comment]
@firrae  You could follow this script which works on our CI Windows Machine:
https://github.com/pmq20/node-compiler/blob/master/appveyor.yml

Otherwise, you could try downloading https://github.com/pmq20/squashfuse/files/691217/sqfs43-win32.zip  and unzipping them to `C:\Windows`.

**Comment by thegreatkang** [comment]
I'm having the same issue on windows as well. tried unzipping to C:\Windows but its still asking for installation. gives me the following error:

```
-> Running ["mksquashfs -version"]
=== HINT ===
Failed exectuing mksquashfs. Have you installed SquashFS Tools?
- On Windows, you could download it from https://github.com/pmq20/squashfuse/files/691217/sqfs43-win32.zip
- On macOS, you could install by using brew: brew install squashfs
- On Linux, you could install via apt or yum, or build from source after downloading source from http://squashfs.sourceforge.net/

C:/__enclose_io_memfs__/_local_/lib/compiler/utils.rb:26:in `spawn': No such file or directory - mksquashfs -version (Errno::ENOENT)
```

**Comment by pmq20** [comment]
@thegreatkang Please try the following and tell me their output ( in order to diagnose),

First open cmd, then,

```
mksquashfs -version
where mksquashfs
dir C:\Windows\mksquashfs.exe
C:\Windows\mksquashfs.exe -version
```

**Comment by thegreatkang** [comment]
@pmq20 i managed to find the problem by using mksquashfs -version you mentioned, i had to copy out the entire content of the folder onto c:\windows (initially i left it untouched after unzipping). now im running into Failed running ["call vcbuild.bat  x64"] problem, will try to resolve it. thanks for the amazing work!

**Comment by firrae** [comment]
I will try this as soon as I get back to work on Monday. Thanks!

**Comment by firrae** [comment]
This seems to be working now. I will update if there are any other issues I encounter.

Thanks!

**Comment by rameres8** [comment]
how to compress squashfs-root files
