### ISSUE TITLE
Prerequisites on Windows

### ISSUE THREAD

**Issue by snewell92** [pmq20/node-compiler#44]
The [installation instructions](https://github.com/pmq20/node-compiler#install-on-windows) say to install both **VS 2013** and **VS 2017** - why both? In another issue (#43) I saw [that the CI build was referenced](https://github.com/pmq20/node-compiler/blob/master/appveyor.yml)  - would following the CI commands suffice to complete the pre-reqs and then install nodec?

If so, could the installation instructions for windows on the readme be updated? Directly downloading python/ruby/squash/node/npm seems more doable and easier to pitch to ~my~ any team than having to download two version of visual studio, and then also needing to use the visual studio shell. (Can't I just use git bash or power shell?) Now, most teams interested in this actually already might have both visual studios, but maybe not. Maybe they're a custom nodejs shop and have cross platform teams working in vim / vscode / sublime / atom etc.

But idk, maybe not.

Thanks for reading <3<3 Feel free to disregard / close. If those instructions are what's needed, than that's that. Just an honest question 😃 

$.02

**Comment by pmq20** [comment]
It's not both. Either should suffice. Let me update the readme. Following CI commands could serve as a good example to make it work.

**Comment by snewell92** [comment]
Thanks @pmq20
