### ISSUE TITLE
/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found

### ISSUE THREAD

**Issue by m31271n** [pmq20/node-compiler#58]
I know, this is a problem of shared lib.

I compiled my app on a gentoo box with glibc-2.23. Then put it on a CentOS  7 box with glibc-2.17.
+ gentoo box: run compiled app perfectly.
+ centos 7: Bang with following information:

> jet is my app.

```
./jet: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by ./jet)
./jet: /lib64/libstdc++.so.6: version `GLIBCXX_3.4.21' not found (required by ./jet)
```

Do not know how to solve this problem. Can you help to solve it? What kind of information should I provide for you ?

**Comment by pmq20** [comment]
Obviously you are using a more recent version of gcc/g++ on your build environment than your run-time environment. Just use an older version of toolchain when compiling could solve the problem.

**Comment by m31271n** [comment]
Got it.

**Comment by m31271n** [comment]
By the way, is there any way to build universal binary to run on all linux regardless of the compile environment?

**Comment by pmq20** [comment]
I don't thin kthere is
