### ISSUE TITLE
how to get the right application working directory, not /__enclose_io_memfs__/

### ISSUE THREAD

**Issue by Huyangfan** [pmq20/node-compiler#61]
I compiled my node project with nodec-x64.exe v1.2.0 on windows 10, everything works fine except that when I use 'path.normalize(__dirname + '/..')' it turns out to be like 'C:\\__enclose_io_memfs__\...' instead of my real application directory(c:\Users\frank\github\myapp\).
I tried to specify the root using 'nodec.exe  --root=./  server.js ', results the same.
so how can I get the right working directory.

**Comment by pmq20** [comment]
Use `process.cwd()`.

**Comment by geekycompy** [comment]
Should all places where __dirname is used be replaced with process.cwd()? Is it possible to include all those files inside the output without making changes to the source code?

**Comment by pmq20** [comment]
@geekycompy You should not need to replace anything. Whatever works BEFORE compiling works AFTER compiling; otherwise it is a bug.

**Comment by Huyangfan** [comment]
@pmq20 Thanks.
